/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tvUAJHkF3Dt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuCheckboxItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function First() {
  return (
    (<div className="flex flex-col min-h-screen bg-background text-foreground">
      <header
        className="flex items-center justify-between h-16 px-6 border-b border-muted">
        <div className="flex items-center gap-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <img
              src="/placeholder.svg"
              width={32}
              height={32}
              alt="Birth Photography Competition" />
            <span className="font-bold text-lg">Birth Photography</span>
          </Link>
        </div>
        <div className="flex items-center gap-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="rounded-full">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Judging Portal</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Profile</DropdownMenuItem>
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <div className="flex flex-1">
        <nav className="hidden md:flex flex-col gap-2 border-r border-muted p-4">
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 bg-accent text-accent-foreground font-medium"
            prefetch={false}>
            <HomeIcon className="w-5 h-5" />
            Home
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 hover:bg-muted/50 transition-colors"
            prefetch={false}>
            <ImageIcon className="w-5 h-5" />
            Entries
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 hover:bg-muted/50 transition-colors"
            prefetch={false}>
            <StarIcon className="w-5 h-5" />
            Scores
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 hover:bg-muted/50 transition-colors"
            prefetch={false}>
            <MessageCircleIcon className="w-5 h-5" />
            Feedback
          </Link>
        </nav>
        <main className="flex-1 p-6">
          <section className="mb-8">
            <h1 className="text-2xl font-bold">Welcome, Judge John Doe</h1>
            <p className="text-muted-foreground">
              You are currently judging the 2023 Birth Photography Competition. There are{" "}
              <span className="font-medium">120 entries</span> to review and score.
            </p>
          </section>
          <section>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xl font-bold">Entries</h2>
              <div className="flex items-center gap-2">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline" size="sm" className="flex items-center gap-2">
                      <FilterIcon className="w-4 h-4" />
                      <span>Filter</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuLabel>Filter by:</DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuCheckboxItem checked>Unscored</DropdownMenuCheckboxItem>
                    <DropdownMenuCheckboxItem>Scored</DropdownMenuCheckboxItem>
                    <DropdownMenuCheckboxItem>Feedback Provided</DropdownMenuCheckboxItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <Button variant="outline" size="sm" className="flex items-center gap-2">
                  <ListOrderedIcon className="w-4 h-4" />
                  <span>Sort</span>
                </Button>
              </div>
            </div>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              <Card className="relative overflow-hidden group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false} />
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={200}
                  alt="Entry Thumbnail"
                  className="object-cover aspect-[3/2] group-hover:scale-105 transition-transform" />
                <CardContent className="p-4">
                  <div className="font-medium">Jane Doe</div>
                  <p className="text-sm text-muted-foreground line-clamp-2">
                    This image captures the beauty and intimacy of a newborn's first moments.
                  </p>
                </CardContent>
                <CardFooter className="flex items-center justify-between p-4 bg-muted/50">
                  <div className="flex items-center gap-2">
                    <StarIcon className="w-4 h-4 text-primary" />
                    <span className="font-medium">4.8</span>
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    Unscored
                  </Badge>
                </CardFooter>
              </Card>
            </div>
          </section>
        </main>
      </div>
      <footer
        className="flex items-center justify-between h-16 px-6 border-t border-muted text-sm text-muted-foreground">
        <p>&copy; 2023 Birth Photography Competition. All rights reserved.</p>
        <div className="flex items-center gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
        </div>
      </footer>
    </div>)
  );
}

function FilterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function ImageIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>)
  );
}


function ListOrderedIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="10" x2="21" y1="6" y2="6" />
      <line x1="10" x2="21" y1="12" y2="12" />
      <line x1="10" x2="21" y1="18" y2="18" />
      <path d="M4 6h1v4" />
      <path d="M4 10h2" />
      <path d="M6 18H4c0-1 2-2 2-3s-1-1.5-2-1" />
    </svg>)
  );
}


function MessageCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
