/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ChX3LnHELIk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Pagination, PaginationContent, PaginationItem, PaginationPrevious, PaginationLink, PaginationNext } from "@/components/ui/pagination"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function Second() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 shadow">
        <div className="container mx-auto flex items-center justify-between">
          <Link
            href="#"
            className="flex items-center gap-2 font-semibold text-lg"
            prefetch={false}>
            <CameraIcon className="h-6 w-6" />
            Birth Photography Competition
          </Link>
          <nav className="hidden md:flex items-center gap-4">
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              About
            </Link>
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              Gallery
            </Link>
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              Rules
            </Link>
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="secondary" size="sm" className="hidden md:inline-flex">
            Submit Entry
          </Button>
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="ghost" size="icon" className="md:hidden">
                <MenuIcon className="h-6 w-6" />
                <span className="sr-only">Toggle navigation</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="right" className="w-[280px]">
              <div className="flex flex-col gap-4 p-6">
                <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
                  About
                </Link>
                <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
                  Gallery
                </Link>
                <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
                  Rules
                </Link>
                <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
                  Contact
                </Link>
                <Button variant="secondary" size="sm" className="w-full">
                  Submit Entry
                </Button>
              </div>
            </SheetContent>
          </Sheet>
        </div>
      </header>
      <main className="flex-1 container mx-auto py-12 px-6 md:px-8 lg:px-10">
        <section className="mb-12">
          <h1 className="text-3xl font-bold mb-4">Welcome to the Birth Photography Competition</h1>
          <p className="text-muted-foreground mb-6">
            Capture the beauty and emotion of birth through your lens and enter our annual competition.
          </p>
          <Button size="sm" className="mb-8">
            Submit Entry
          </Button>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">Featured Entries</h2>
          <ScrollArea className="h-[400px] mb-6">
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {[...Array(12)].map((_, i) => (
                <Card key={i} className="overflow-hidden">
                  <CardContent className="p-0">
                    <img
                      src="/placeholder.svg"
                      alt={`Entry ${i + 1}`}
                      width={400}
                      height={300}
                      className="object-cover w-full aspect-[4/3]" />
                  </CardContent>
                  <CardFooter className="px-4 py-3">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <div>
                          <p className="text-sm font-medium">John Doe</p>
                          <p className="text-xs text-muted-foreground">Photographer</p>
                        </div>
                      </div>
                      <Badge variant="secondary">Finalist</Badge>
                    </div>
                  </CardFooter>
                </Card>
              ))}
            </div>
          </ScrollArea>
          <div className="flex justify-end">
            <Pagination>
              <PaginationContent>
                <PaginationItem>
                  <PaginationPrevious href="#" />
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#" isActive>
                    1
                  </PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#">3</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationNext href="#" />
                </PaginationItem>
              </PaginationContent>
            </Pagination>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">Judges' Picks</h2>
          <ScrollArea className="h-[400px] mb-6">
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {[...Array(8)].map((_, i) => (
                <Card key={i} className="overflow-hidden">
                  <CardContent className="p-0">
                    <img
                      src="/placeholder.svg"
                      alt={`Judge's Pick ${i + 1}`}
                      width={400}
                      height={300}
                      className="object-cover w-full aspect-[4/3]" />
                  </CardContent>
                  <CardFooter className="px-4 py-3">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <div>
                          <p className="text-sm font-medium">Jane Doe</p>
                          <p className="text-xs text-muted-foreground">Judge</p>
                        </div>
                      </div>
                      <Badge>Winner</Badge>
                    </div>
                  </CardFooter>
                </Card>
              ))}
            </div>
          </ScrollArea>
          <div className="flex justify-end">
            <Pagination>
              <PaginationContent>
                <PaginationItem>
                  <PaginationPrevious href="#" />
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#" isActive>
                    1
                  </PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#">3</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationNext href="#" />
                </PaginationItem>
              </PaginationContent>
            </Pagination>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">Participant Leaderboard</h2>
          <ScrollArea className="h-[400px] mb-6">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Rank</TableHead>
                  <TableHead>Photographer</TableHead>
                  <TableHead>Entries</TableHead>
                  <TableHead>Badges</TableHead>
                  <TableHead>Score</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {[...Array(10)].map((_, i) => (
                  <TableRow key={i}>
                    <TableCell>{i + 1}</TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <div>
                          <p className="text-sm font-medium">John Doe {i + 1}</p>
                          <p className="text-xs text-muted-foreground">Photographer</p>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>12</TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Badge variant="secondary">Finalist</Badge>
                        <Badge>Winner</Badge>
                      </div>
                    </TableCell>
                    <TableCell>98</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </ScrollArea>
          <div className="flex justify-end">
            <Pagination>
              <PaginationContent>
                <PaginationItem>
                  <PaginationPrevious href="#" />
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#" isActive>
                    1
                  </PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#">3</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationNext href="#" />
                </PaginationItem>
              </PaginationContent>
            </Pagination>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">Upcoming Events</h2>
          <ScrollArea className="h-[400px] mb-6">
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {[...Array(8)].map((_, i) => (
                <Card key={i} className="overflow-hidden">
                  <CardContent className="p-0">
                    <img
                      src="/placeholder.svg"
                      alt={`Event ${i + 1}`}
                      width={400}
                      height={300}
                      className="object-cover w-full aspect-[4/3]" />
                  </CardContent>
                  <CardFooter className="px-4 py-3">
                    <div className="flex flex-col gap-2">
                      <div className="flex items-center justify-between">
                        <p className="text-sm font-medium">Event {i + 1}</p>
                        <Badge variant="secondary">Upcoming</Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">June 1, 2023 - June 30, 2023</p>
                    </div>
                  </CardFooter>
                </Card>
              ))}
            </div>
          </ScrollArea>
          <div className="flex justify-end">
            <Pagination>
              <PaginationContent>
                <PaginationItem>
                  <PaginationPrevious href="#" />
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#" isActive>
                    1
                  </PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationLink href="#">3</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                  <PaginationNext href="#" />
                </PaginationItem>
              </PaginationContent>
            </Pagination>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-6 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm">&copy; 2023 Birth Photography Competition</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="hover:text-muted-foreground/80" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="hover:text-muted-foreground/80" prefetch={false}>
              Terms of Service
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function CameraIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
      <circle cx="12" cy="13" r="3" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
